name:                bench
version:             0.2.1.0
github:              "githubuser/bench"
license:             BSD3
author:              "Phil Curzon"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bench#readme>

dependencies:
- base >= 4.7 && < 5
- criterion
- uri-bytestring
- deepseq
- weigh
- bytestring

benchmarks:
  bench-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -rtsopts
    - '"-with-rtsopts=-T"'
    - +RTS -T -RTS
    dependencies:
    - dormouse-uri

    
