name:                dormouse-client
version:             0.2.0.0
github:              "theinnerlight/dormouse"
license:             BSD3
author:              Phil Curzon
maintainer:          "phil@novelfs.org"
copyright:           "2020-2021 Phil Curzon"
homepage:            "https://dormouse.io/client.html"
license-file:        "LICENSE"

extra-source-files:
- README.md
- ChangeLog.md

extra-doc-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple, type-safe and testable HTTP client
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: | 
  An HTTP client designed to be productive, easy to use, easy to test, flexible and safe!
  
  It was designed with the following objectives in mind:
       
    - HTTP requests and responses should be modelled by a simple, immutable Haskell Record.
    - Actual HTTP calls should be made via an abstraction layer (`MonadDormouseClient`) so testing and mocking is painless.
    - Illegal requests should be unrepresentable, such as HTTP GET requests with a content body.
    - It should be possible to enforce a protocol (e.g. https) at the type level.
    - It should be possible to handle large request and response bodies via constant memory streaming.

  Please see https://dormouse.io for full documentation.

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13.2.4 && < 0.14
- bytestring >= 0.10.8 && < 0.11.0
- aeson >= 1.4.2 && < 2.0.0
- http-api-data >= 0.4.1.1 && < 0.5
- http-client >= 0.6.4.1 && < 0.7.0
- http-client-tls >= 0.3.5.3 && < 0.4
- safe-exceptions >= 0.1.7 && < 0.2.0
- case-insensitive >= 1.2.1.0 && < 2.0.0
- http-types >= 0.12.3 && < 0.13
- text >= 1.2.4 && < 2.0.0
- mtl >= 2.2.2 && < 3
- template-haskell >= 2.15.0 && < 3.0.0
- streamly >= 0.7.2 && < 0.8
- streamly-bytestring >= 0.1.2 && < 0.2
- containers >= 0.6.2.1 && < 0.7

library:
  source-dirs: src
  exposed-modules:
    - Dormouse.Client
    - Dormouse.Client.Headers
    - Dormouse.Client.Headers.MediaType
    - Dormouse.Client.MonadIOImpl
    - Dormouse.Client.Status
    - Dormouse.Client.Test.Class
  dependencies:
    - dormouse-uri
  ghc-options:
    - -Wall
  
tests:
  dormouse-client-test:
    main:                Spec.hs
    source-dirs:         
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fdicts-strict
    dependencies:
    - dormouse-uri
    - hspec >= 2.0.0 && < 3
    - hspec-discover >= 2.0.0 && < 3
    - hedgehog >= 1.0.1 && < 2
    - hspec-hedgehog >= 0.0.1.2 && < 0.1
    - scientific >= 0.3.6.2 && < 0.4
    - vector >= 0.12.0.3 && < 0.13

default-extensions:
  - OverloadedStrings
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - FlexibleContexts
