name:                dormouse-examples
version:             0.3.0.0
github:              "githubuser/dormouse"
license:             BSD3
author:              Phil Curzon
maintainer:          "phil@novelfs.org"
copyright:           "2020 Phil Curzon"

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13.2.4 && < 0.15
- bytestring >= 0.10.8 && < 0.12.0
- aeson >= 2.0 && < 3.0
- http-api-data >= 0.4.1.1 && < 0.6
- http-client >= 0.6.4.1 && < 0.8.0
- http-client-tls >= 0.3.5.3 && < 0.4
- safe-exceptions >= 0.1.7 && < 0.2.0
- case-insensitive >= 1.2.1.0 && < 2.0.0
- http-types >= 0.12.3 && < 0.13
- text >= 2.0.0 && < 3.0.0
- mtl >= 2.2.2 && < 3
- template-haskell >= 2.15.0 && < 3.0.0
- streamly
- streamly-core
- streamly-bytestring
- containers >= 0.6.2.1 && < 0.7
  
executables:
  dormouse-examples:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dormouse-client
    - dormouse-uri
   
default-extensions:
  - OverloadedStrings
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - FlexibleContexts
